### PR TITLE
Rewrote HelpBox to MUI, fixed overflow bug

### LINKED ISSUE #452: Fix Help Box Overflow
https://github.com/icssc/AntAlmanac/pull/450#pullrequestreview-1195222815
image

The grey thing at the bottom is a horizontal scroll bar. Ideally, we want the images to automatically scale down so all 3 fit in the window at all times. The fix is probably something in the flexbox settings properties or converting this component to CSS grid instead of flexbox.

### PR DESCRIPTION
**Pull request by KevinWu098**
## Summary
By rewriting it to MUI, the HelpBox overflow/sizing issues were removed. 

Before:
Before

After:
After

## Test Plan
Resizing works fine, no overflow issues.

## Issues
Closes #452 

## Additional Notes/RFC
Currently, `SearchForm.tsx` only renders the HelpBox in September and October. Should this behavior be changed to:
1. Render in Sep/Oct AND Dec/Jan AND Mar/Apr (AND Jun/Jul)
2. Always Render
3. Remain the same :)

### CODE REVIEW

**Comment by KevinWu098** [comment]
Before merging, I'll need to remove the comments that are allowing the HelpBox to show in June!

> `{/*(currentMonth === 8 || currentMonth === 9) &&*/ <HelpBox />}`

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx [hunk 1]
```diff
@@ -1,62 +1,62 @@
 import { Paper, withStyles } from '@material-ui/core';
 import { ClassNameMap } from '@material-ui/core/styles/withStyles';
+import { ImageList, ImageListItem, Typography } from '@mui/material';
 
 const styles = {
     container: {
         padding: 12,
         marginBottom: '10px',
         marginRight: '5px',
     },
```
Comment (ap0nia) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx]: Use MUIv5's [`sx`](https://mui.com/system/getting-started/the-sx-prop/) prop instead of `withStyles`

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx [hunk 2]
```diff
@@ -1,62 +1,62 @@
 import { Paper, withStyles } from '@material-ui/core';
 import { ClassNameMap } from '@material-ui/core/styles/withStyles';
```
Comment (ap0nia) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx]: Don't use components from both MUIv4 and v5; commit to MUIv5

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx [hunk 3]
```diff
@@ -1,62 +1,62 @@
...
-                    className={classes.image}
-                    src="/helpbox3.png"
-                    alt='Electrical Engineering page with "REQUIREMENTS" and "SAMPLE PROGRAM" tabs highlighted'
-                />
-            </div>
+            <Typography variant="h5" fontWeight={'bold'}>
+                Need help planning your schedule?
+            </Typography>
+            <Typography>
+                <ol>
```
Comment (ap0nia) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx]: Try using MUI's [`List` component](https://mui.com/joy-ui/react-list/)

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx [hunk 4]
```diff
@@ -1,62 +1,62 @@
...
+                    <li>
+                        Browse undergraduate majors on the{' '}
+                        <a
```
Comment (ap0nia) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx]: Try using MUI's [`Link` component](https://mui.com/joy-ui/react-link/)

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx [hunk 5]
```diff
@@ -1,62 +1,62 @@
...
+                        should take.
+                    </li>
+                </ol>
+            </Typography>
+            <ImageList gap={10} cols={3}>
+                <ImageListItem>
+                    <img
+                        src="/helpbox1.png"
+                        alt='UCI General Catalogue with "Explore Undergraduate Programs" button highlighted'
+                    />
```
Comment (ap0nia) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx]:
```suggestion
                    <Box
                       component="img"
                        src="/helpbox1.png"
                        alt='UCI General Catalogue with "Explore Undergraduate Programs" button highlighted'
                    />
```
ngl, this is kinda cursed, so maybe it's not worth doing lol.

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/SearchForm.tsx [hunk 6]
```diff
@@ -106,7 +108,7 @@ const SearchForm = (props: { classes: ClassNameMap; toggleSearch: () => void })
                 </div>
             </form>
 
-            {(currentMonth === 8 || currentMonth === 9) && <HelpBox />}
+            {/*(currentMonth === 8 || currentMonth === 9) &&*/ <HelpBox />}
```
Comment (ap0nia) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/SearchForm.tsx]: Initialize `currentMonth` outside of this component so it doesn't ever have to be recalculated per re-render.
Create an array of months (also outside the component) that it should be active.
```suggestion
            const activeMonthIndices = [false, false, false, false, false, false, false, true, true, false, false, false]
            {/* activeMonthIndices[currentMonthIndex] && */ <HelpBox />}
```

**Review by ap0nia — CHANGES_REQUESTED** [review]
Adjust for some minor inconsistencies

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx (hunk 5 above)
Comment (KevinWu098) [reply apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/HelpBox.tsx]:
```typescript
        <ImageListItem key={item.img}>
          <img
            src={`${item.img}?w=164&h=164&fit=crop&auto=format`}
            srcSet={`${item.img}?w=164&h=164&fit=crop&auto=format&dpr=2 2x`}
            alt={item.title}
            loading="lazy"
          />
        </ImageListItem>
```

This is how [MUI](https://mui.com/material-ui/react-image-list/) demos `ImageListItem`, so I think I'll pass on the cursed box 👻

**Review by ap0nia — APPROVED** [review]
Looks good :rocket:

**Review by ap0nia — APPROVED** [review]
LGTM :rocket:
