### PR TITLE
Fix ColorPicker not showing section color right after adding.

### LINKED ISSUE #510: Color picker colors broken in search results
When you add a class, the color picker in the section table doesn't get the right color until you reload the results. The icon is white and the color it opens to isn't the actual color of the section added.
Seems like the bug was introduced in #457.
image

### PR DESCRIPTION
**Pull request by EricPedley**
## Summary
Fixes a bug where the colorpicker in the sectiontable wouldn't immediately change to the color of an added course.

I figured this one out by re-reading the diff for #457 and looking specifically at the logic around addCourse. This long return chain is how we did it before and it feels kinda janky but I would rather have a patch out than spend a bunch of time architecting a more elegant solution.

## Test Plan
Verify that courses colors are displayed correctly on the color picker immediately after they're added.
## Issues

Closes #510

### CODE REVIEW

**Review by ap0nia — CHANGES_REQUESTED** [review]
I think `addCourse` should return the course that was added, or an object with all the necessary information about the course that can be used by other functions. I think this makes the most sense without knowing much about the function; and it also gives you more flexibility to use the returned object in other contexts. (you would then extract the desired properties from the object, i.e. the color for this patch)

Also just an optional code clarity note, you can assign values of function return and relevant intermediate steps to make it clearer about what/how you'll use it, e.g
```ts
// AppStore
const newCourse = ...
const newCourseWithColor = {...newCourse, color: 'color' }
return newCourseWithColor

// invocation/use-case
const newCourseAdded = AppStore.addCourse(...)
const newColor = newCourseAdded.color
```

Specifically returning a color makes the function coupled to this specific scenario and use-case, which might encourage hacky work arounds in the future

File: src/components/RightPane/SectionTable/SectionTableButtons.tsx [hunk 1]
```diff
@@ -85,7 +85,7 @@ export const ScheduleAddCell = withStyles(styles)((props: ScheduleAddCellProps)
                     action: analyticsEnum.classSearch.actions.ADD_SPECIFIC,
                 });
             }
-            section.color = addCourse(section, courseDetails, term, scheduleIndex);
+            section.color = addCourse(section, courseDetails, term, scheduleIndex).section.color;
```
Comment (ap0nia) [inline src/components/RightPane/SectionTable/SectionTableButtons.tsx]:
```suggestion
            const newCourse = addCourse(section, courseDetails, term, scheduleIndex).section.color;
            section.color = newCourse.section.color
```
Optional: you can a temp variable to make it clearer

File: src/stores/AppStore.ts [hunk 2]
```diff
@@ -66,15 +66,15 @@ class AppStore extends EventEmitter {
...
 
     addCourse(newCourse: ScheduleCourse, scheduleIndex: number = this.schedule.getCurrentScheduleIndex()) {
-        let color: string;
+        let addedCourse: ScheduleCourse;
         if (scheduleIndex === this.schedule.getNumberOfSchedules()) {
-            color = this.schedule.addCourseToAllSchedules(newCourse);
+            addedCourse = this.schedule.addCourseToAllSchedules(newCourse);
         } else {
-            color = this.schedule.addCourse(newCourse);
+            addedCourse = this.schedule.addCourse(newCourse);
```
Comment (ap0nia) [inline src/stores/AppStore.ts]:
```ts
const addedCourse = 
scheduleIndex === this.schedule.getNumberOfSchedules() ?
    this.schedule.addCourseToAllSchedules(newCourse) : 
    this.schedule.addCourse(newCourse)
```

Optional: doing this allows TypeScript to infer the return type implicitly; downside is that it's harder to read

File: src/actions/AppStoreActions.ts [hunk 3]
```diff
@@ -38,7 +38,7 @@ export const addCourse = (
         section: { ...section, color: '' },
     };
 
-    AppStore.addCourse(newCourse, scheduleIndex);
+    return AppStore.addCourse(newCourse, scheduleIndex);
```
Comment (ap0nia) [inline src/actions/AppStoreActions.ts:41]:
```suggestion
    const addedCourse = AppStore.addCourse(newCourse, scheduleIndex);
    return addedCourse;
```
Optional: more clear what we're doing without requiring knowledge of the `addCourse` method

**Review by ap0nia — APPROVED** [review]
I think this is acceptable for shipping! 🚀 

IMO I don't think this "return chain" strategy is necessarily wrong; I've implemented a similar strategy in my stores re-write, but with less levels of indirection. I think clearly communicating returned interfaces is good for making existing functionality more reusable and quickly implementing features without having to go down to the root store to augment behavior for new, specific use cases
