### PR TITLE
fix: isDark fixes

### LINKED ISSUE #877: Preview in Zotistics causes the website to crash
If you search a course, and you want to get a preview of Zotistics by leaving your mouse on top of the Zotistics button, this error message pops up and causes the whole website to crash:
image

### PR DESCRIPTION
**Pull request by KevinWu098**
## Summary
1. Misc. fixes where `appTheme` was still being used instead of `isDark`.
2. Took some liberties also to handle eslint warnings

## Test Plan
1. The button styling in settings menu should work as expected on all modes
2. Zotistics popup should work as expected (correct axis colors, no crash)

## Issues
Closes #877

### CODE REVIEW

File: apps/antalmanac/src/components/RightPane/SectionTable/GradesPopup.tsx [hunk 1]
```diff
@@ -69,12 +69,12 @@ function GradesPopup(props: GradesPopupProps) {
...
               } | Average GPA: ${gradeData.courseGrades.averageGPA.toFixed(2)}`
             : 'Grades are not available for this class.';
-    }, [deptCode, instructor, gradeData]);
+    }, [gradeData, deptCode, courseNumber, instructor]);
 
-    const gpaString = useMemo(
-        () => (gradeData ? `Average GPA: ${gradeData.courseGrades.averageGPA.toFixed(2)}` : ''),
-        [gradeData]
-    );
+    // const gpaString = useMemo(
```
Comment (EricPedley) [inline apps/antalmanac/src/components/RightPane/SectionTable/GradesPopup.tsx:74]: why does this need to be commented out?

**Review by EricPedley — CHANGES_REQUESTED** [review]
1 question to answer, otherwise looks good

File: apps/antalmanac/src/components/RightPane/SectionTable/GradesPopup.tsx (hunk 1 above)
Comment (KevinWu098) [reply apps/antalmanac/src/components/RightPane/SectionTable/GradesPopup.tsx:74]: Wasn't being used, so I took some liberties since I was in the file 😅 . Can revert if pref.

Comment (EricPedley) [reply apps/antalmanac/src/components/RightPane/SectionTable/GradesPopup.tsx:74]: eh it's whatever. This tech debt isn't very high-interest.

**Review by EricPedley — APPROVED** [review]
