### PR TITLE
fix: update fall 2023 instruction start date

### LINKED ISSUE #562: `termData.ts` Inconsistent Dates
The [`termData.ts`](https://github.com/icssc/AntAlmanac/blob/main/apps/antalmanac/src/lib/termData.ts) file that contains the active terms, with their start dates. Some start dates are set as the beginning of the quarter, while others are the start of instruction.

```ts
const termData = [
    new Term('2023 Fall', '2023 Fall Quarter', [2023, 8, 25]), // <- Start of quarter
    new Term('2023 Summer2', '2023 Summer Session 2', [2023, 7, 7]),
    new Term('2023 Summer10wk', '2023 10-wk Summer', [2023, 5, 26]),
    new Term('2023 Summer1', '2023 Summer Session 1', [2023, 5, 26]),
    new Term('2023 Spring', '2023 Spring Quarter', [2023, 3, 3]),
    new Term('2023 Winter', '2023 Winter Quarter', [2023, 0, 9]),
    new Term('2022 Fall', '2022 Fall Quarter', [2022, 8, 22]), // <- Instruction begins
    new Term('2022 Summer2', '2022 Summer Session 2', [2022, 7, 1]),
    // ...
]
```

Super minor issue, but I'll open a PR validating these date, adding a comment, and backfilling missing dates.

### PR DESCRIPTION
**Pull request by ecxyzzy**
## Summary

Update the Fall 2023 instruction start date, since the calendar import is currently broken. Also add clarifying comments for future maintainers.

## Test Plan

Import an exported schedule into GCal and see that it isn't scuffed.

From prod:
image

From local dev server after this patch:
image

## Issues

n/a

### CODE REVIEW

**Comment by ecxyzzy** [comment]
Oh oops I did not realize that #562 is a thing.

File: apps/antalmanac/src/lib/termData.ts [hunk 1]
```diff
@@ -12,10 +12,11 @@ class Term {
     }
 }
 
-// Quarterly Academic Calendar: https://www.reg.uci.edu/calendars/quarterly/2022-2023/quarterly22-23.html
+// Quarterly Academic Calendar: https://www.reg.uci.edu/calendars/quarterly/2023-2024/quarterly23-24.html
+// The `startDate`, if available, should correspond to the instruction start date (not the quarter start date)
 // Note: months are 0-indexed
```
Comment (ap0nia) [inline apps/antalmanac/src/lib/termData.ts]:
```suggestion
/**
 * Quarterly Academic Calendar {@link https://www.reg.uci.edu/calendars/quarterly/2023-2024/quarterly23-24.html}
 * The `startDate`, if available, should correspond to the __instruction start date__ (not the quarter start date)
 * Months are 0-indexed
 */
```
JSDoc diff?

**Comment by EricPedley** [comment]
Why `no deploy`?

**Comment by ecxyzzy** [comment]
I figured we probably didn't need to waste our AWS resources for a small change like this, since I tested locally and it worked. If it's SOP to deploy for any change lmk and I'll remove the tag.

**Comment by EricPedley** [comment]
How limited are we by AWS resources? I was making it SOP to do preview deployments because I was under the impression it was basically zero-cost for us, but if it actually increases our bill I guess we can only preview-deploy big changes.

**Comment by ecxyzzy** [comment]
You're probably right that it's "basically zero-cost" and I'm not sure about the specific amount per staging build, but it shouldn't matter that much (I think if it did matter, route53 and s3 would be the "biggest" offenders). It just feels weird doing a staging build for a one-line code change.

**Review by EricPedley — APPROVED** [review]
lgtm 🚢

**Comment by ap0nia** [comment]
The correct mindset:
