### PR TITLE
Fix warnings

### LINKED ISSUE #163: Invalid Action Type Warnings for Every Action
Open up the console and try doing anything (LOAD_SCHEDULE, OPEN_SNACKBAR, CLEAR_SCHEDULE, TAB_CHANGE, ADD_COURSE, DELETE_COURSE, UPDATE_FORM_FIELD). Every action should work but also give an "invalid action type" warning.

The one exception is DELETE_COURSE in the Added Classes pane. I can't figure out how to reproduce it anymore, but sometimes it would not delete the first course listed when clicking delete.

image

### LINKED ISSUE #199: Fix console warnings
The console is logging warnings for lots of different things

- [x] AppStore invalid action type
- [x] RightPane invalid action type
- [x] Function components cannot be given refs
- [x] Each child in a list should have a unique "key" prop.
- [x] Material-UI: theme.spacing.unit usage has been deprecated.
- [x] /SectionTableBody.js Line 340:8:  React Hook useEffect has missing dependencies:

### PR DESCRIPTION
**Pull request by EricPedley**
## Summary
Fixed a bunch of console warnings. After this PR, there shouldn't be any more warnings in the console.
## Test Plan
Click on all the places on the site and ensure that no warnings appear in the console upon doing any action.
## Issues
Closes #199, #163

### CODE REVIEW

**Comment by EricPedley** [comment]
This is a draft because I don't have the .env yet and there are still some errors when I run the frontend locally that I want to confirm will go away once I run the client with the backend.

File: client/src/stores/AppStore.js [hunk 1]
```diff
@@ -217,8 +217,7 @@ class AppStore extends EventEmitter {
                 this.emit('themeToggle');
                 window.localStorage.setItem('theme', action.theme);
                 break;
-            default:
-                console.log(`[Warning] AppStore invalid action type: ${action.type}`);
+            default: //do nothing
```
Comment (ChaseC99) [inline client/src/stores/AppStore.js:220]: This works for now, but we may want to refactor so that we aren't using multiple stores for AppStore and RightPaneStore

**Review by ChaseC99 — CHANGES_REQUESTED** [review]
A lot of great work so far; the console is looking hecka clean.

There are still some errors on the "Added Classes" and "Map" tabs. Could you take a look into these? 
_(loaded class schedule was called `test`)_

image

File: client/src/stores/AppStore.js (hunk 1 above)
Comment (EricPedley) [reply client/src/stores/AppStore.js:220]: Opened an issue for this

**Comment by ChaseC99** [comment]
Still getting a key error for the map, when I click on "Tuesday"
image

File: client/src/components/App/ConditionalWrapper.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import React from 'react';
+
+const ConditionalWrapper = React.forwardRef(({ condition, wrapper, children }, ref) => {
+    return condition ? wrapper(children) : children;
+});
```
Comment (ChaseC99) [inline client/src/components/App/ConditionalWrapper.js:5]: This is a good abstraction 👍

**Comment by ChaseC99** [comment]
I think this is probably where the issue is coming from but I'm not totally sure:
https://github.com/icssc-projects/AntAlmanac/blob/fix-warnings/client/src/components/Map/UCIMap.js#L119

Also important note - @falsidge updated UCIMap.js in #223. So you'll probably need to merge in the latest version of `main`.

**Review by ChaseC99 — APPROVED** [review]
YAY GREAT WORK 🎉  

This PR ended up being wayyyyyy more work than anticipated lol. Great job powering through all of the warnings/errors to clean up our dev environment. While these code changes might not be as glamours as a new feature, it's just as important - if not more - to the longterm success of the project.

Let's 🚢  it
