### PR TITLE
Minor UI Fix to School/Dept Cards

### LINKED ISSUE #583: Comments Card Should be Clickable
The entire comments card should be clickable, rather than just the dropdown icon

Comments Card

### PR DESCRIPTION
**Pull request by KevinWu098**
## Summary

- Comment cards on both School and Department can now be opened by clicking the text box, in addition to the already existing dropdown icon.

Before:
Before

After:
After

## Test Plan
Make sure clicking works (it do)

## Issues
Closes #583 

## Additional Notes
It's a bit thicker now that it's an accordion, but I'm not battling the MUI gods over some love handles...

### CODE REVIEW

**Review by MinhxNguyen7 — APPROVED** [review]
Great change. This has been bugging me. Tested and LGTM!

**Review by MinhxNguyen7 — DISMISSED** [review]
I know I approved this, but I changed my mind. The clicking is good. I'm not completely sold on the style change though. It makes the top look cluttered, and it isn't that distinguished in light mode. Can you just remove (reset and rebase) that change? 

That resolves my other concern of not-exactly-atomic PR as well. For the sake of procedural completeness, can you create an issue (something along the lines of "comments card should be clickable") and link this PR? That's the usual workflow; a PR solves an issue.

As for the distinction, if it bothers you, put up an issue, and we can all discuss it.

**Comment by KevinWu098** [comment]
> I know I approved this, but I changed my mind. The clicking is good. I'm not completely sold on the style change though. It makes the top look cluttered, and it isn't that distinguished in light mode. Can you just remove (reset and rebase) that change?
> 
> That resolves my other concern of not-exactly-atomic PR as well. For the sake of procedural completeness, can you create an issue (something along the lines of "comments card should be clickable") and link this PR? That's the usual workflow; a PR solves an issue.
> 
> As for the distinction, if it bothers you, put up an issue, and we can all discuss it.

Had to do a new push rather than a rebase since my initial commits weren't atomic (I can see why atomic PRs are best practice now). Other than that, everything should be good now; an issue was created and linked here

File: apps/antalmanac/src/components/RightPane/CoursePane/SchoolDeptCard.tsx [hunk 1]
```diff
@@ -54,6 +55,10 @@ class SchoolDeptCard extends PureComponent<SchoolDeptCardProps> {
                     <Typography
                         noWrap
                         variant={this.props.type === 'school' ? 'h6' : 'subtitle1'}
+                        onClick={() =>
+                            this.setState({
+                                commentsOpen: !this.state.commentsOpen,
+                            })}
                         className={this.props.classes.text}
                     >
```
Comment (ap0nia) [inline apps/antalmanac/src/components/RightPane/CoursePane/SchoolDeptCard.tsx]: Try not to do things like this; typographic elements like headers, paragraphs, etc. aren't meant to be clicked on or produce side effects as a result -- general WAI/ARIA stuff. The correct fix is to use the [`Accordion`](https://mui.com/material-ui/react-accordion/) MUI component. We shouldn't even have to manage the open/closed state manually.

For reference, here's my implementation of it: https://github.com/icssc/AntAlmanac/blob/aponia-deploy/src/components/Schedule/Department/Department.tsx

^The above was written for MUI5, so you'll have to adjust the imports for MUI4 by changing `import * from '@mui/material'` to `import * from '@material-ui/core'`

**Review by ap0nia — CHANGES_REQUESTED** [review]
Try out the `Accordion` MUI component instead of monkey patching `Typography`; idk why this was even using `Collapse` instead of `Accordion` in the first place.

**Review by ap0nia — DISMISSED** [review]
Try out the `Accordion` MUI component instead of monkey patching `Typography`; idk why this was even using `Collapse` instead of `Accordion` in the first place.

**Review by MinhxNguyen7 — APPROVED** [review]
LGTM, and it's even smoother!

File: apps/antalmanac/src/components/RightPane/CoursePane/SchoolDeptCard.tsx [hunk 2]
```diff
@@ -47,38 +48,28 @@ class SchoolDeptCard extends PureComponent<SchoolDeptCardProps> {
...
                             </Typography>
-                            <div dangerouslySetInnerHTML={html} className={this.props.classes.comments} />
-                        </Collapse>
-                    </>
+                        </AccordionSummary>
+                        <AccordionDetails>
+                                <Typography variant="body2">
+                                    {this.props.comment === '' ? 'No comments found' : 'Comments:'}
+                                    <Box dangerouslySetInnerHTML={html} className={this.props.classes.comments} />
+                                </Typography>
```
Comment (ap0nia) [inline apps/antalmanac/src/components/RightPane/CoursePane/SchoolDeptCard.tsx]:
```suggestion
                                <Typography variant="body2">
                                <p>
                                    {this.props.comment === '' ? 'No comments found' : 'Comments:'}
                                 </p>
                                 <Box dangerouslySetInnerHTML={html} className={this.props.classes.comments}  component="p" />
                                </Typography>
```
Box is a `div` by default I believe; divs shouldn't be nested inside of typographic elements. You can set the `component` prop for Box to make it assume something like a regular paragraph. Also, if there are multiple elements, I like to explicitly wrap sections with some tag so that way it's easier to distinguish them.

**Review by ap0nia — DISMISSED** [review]
Basically looks good. Just adjust the structure of the accordion details. Also run the formatter/linter on the file

**Review by ap0nia — APPROVED** [review]
Good enough, very cool! :rocket: :fire:
