### PR TITLE
fix: align theme palette to planner

### LINKED ISSUE #1467: AA x PP Consolidate Themes
With the merge with PeterPortal we want to unify the the designs as much as possible so that AntAlmanac and PeterPortal appear as one single app. Moving forward we will match PeterPortal's light and dark mode since they follow the MUI conventions. 

The challenge of this issue will be discovery as AntAlmanac has several components that may need to adjusting 

### Light Mode
Image

Image

### Dark Mode:
Image

Image

### PR DESCRIPTION
**Pull request by AureliaSindhu**
## Summary
Update AntAlmanac MUI palette to match PeterPortal light/dark colors.

Light version:
Screenshot 2026-02-04 at 10 22 07 PM
Screenshot 2026-02-04 at 10 22 12 PM
Screenshot 2026-02-04 at 10 22 17 PM

Dark version:
Screenshot 2026-02-10 at 10 29 48 PM
Screenshot 2026-02-04 at 10 21 57 PM
Screenshot 2026-02-04 at 10 22 03 PM

## Test Plan
Toggle theme setting: Light / Dark / System and verify colors update correctly.

## Issues

Closes #1467

### CODE REVIEW

**Review by alexespejo — CHANGES_REQUESTED** [review]
_Hopefully I can cover everything_

### Link text seems too dark. PeterPortal uses the mui-secondary blue on dark mode 

**PP**
Image

**AA**

Image

Image

Image

_These links have always been a different color but maybe there's a consistency thing we can keep here_

### Search button options poorly contrast 

Image

Will discuss :P

**Comment by AureliaSindhu** [comment]
pls lmk if i miss something :)

**Review by alexespejo — CHANGES_REQUESTED** [review]
Formally requesting change. Reference Discord discussiion :)

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearch.tsx [hunk 1]
```diff
@@ -38,7 +40,15 @@ export function AdvancedSearch() {
...
     return (
         <>
-            <Button onClick={handleExpand} sx={{ textTransform: 'none', display: 'flex', justifyContent: 'start' }}>
+            <Button
+                onClick={handleExpand}
+                sx={{
+                    textTransform: 'none',
+                    display: 'flex',
+                    justifyContent: 'start',
+                    color: theme.palette.mode === 'dark' ? theme.palette.secondary.main : undefined,
```
Comment (alexespejo) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearch.tsx]: nit: we have a `useThemeStore` that we use throughout the codebase 

```ts
    const isDark = useThemeStore((store) => store.isDark);
```

question: secondary doesn't work for light mode here? I think for clarity it's a little weird that the fallback is undefined

File: apps/antalmanac/src/components/Header/Settings/ThemeSelector.tsx [hunk 2]
```diff
@@ -60,15 +61,15 @@ export function ThemeSelector() {
...
+                                backgroundColor: isSelected ? accentColor : isDark ? '#333333' : '#f8f9fa',
+                                color: isSelected ? '#fff' : accentColor,
                                 borderRight: index < 2 ? `1px solid ${isDark ? '#8886' : '#d3d4d5'}` : 'none',
                                 borderTopLeftRadius: tab.value === 'light' ? 4 : 0,
                                 borderBottomLeftRadius: tab.value === 'light' ? 4 : 0,
                                 borderTopRightRadius: tab.value === 'dark' ? 4 : 0,
                                 borderBottomRightRadius: tab.value === 'dark' ? 4 : 0,
                                 '&:hover': {
-                                    backgroundColor: isSelected ? BLUE : isDark ? '#424649' : '#d3d4d5',
+                                    backgroundColor: isSelected ? accentColor : isDark ? '#424649' : '#d3d4d5',
```
Comment (alexespejo) [inline apps/antalmanac/src/components/Header/Settings/ThemeSelector.tsx]: issue: consolidate `#424649` and `#d3d4d5` into reusable constants

File: apps/antalmanac/src/components/Header/Settings/TimeSelector.tsx [hunk 3]
```diff
@@ -60,12 +61,12 @@ export function TimeSelector() {
                         cursor: 'pointer',
                         fontWeight: 'bold',
                         fontSize: '1.1rem',
-                        backgroundColor: isMilitaryTime ? BLUE : isDark ? '#333333' : '#f8f9fa',
-                        color: isMilitaryTime ? '#fff' : BLUE,
+                        backgroundColor: isMilitaryTime ? accentColor : isDark ? '#333333' : '#f8f9fa',
```
Comment (alexespejo) [inline apps/antalmanac/src/components/Header/Settings/TimeSelector.tsx]: suggestion: this ternary seems to be repeated a few times in this file should be consolidated

File: apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx [hunk 4]
```diff
@@ -19,13 +22,16 @@ export function ScheduleSelector({ scheduleIndices, onSelectScheduleIndices, sch
 
     return (
         <FormControl style={{ maxWidth: 400 }} fullWidth>
-            <InputLabel variant="outlined">Select schedules</InputLabel>
+            <InputLabel variant="outlined" color={secondaryColor ? 'secondary' : 'primary'}>
```
Comment (alexespejo) [inline apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx]: issue: I believe I'm reading this correctly but `useSecondaryColor` never a falsely value

File: apps/antalmanac/src/components/Header/Settings/TimeSelector.tsx (hunk 3 above)
Comment (alexespejo) [reply apps/antalmanac/src/components/Header/Settings/TimeSelector.tsx]: question: do you need `accentColor`? You can't use 'secondary` since the theme uses the same logic

**Review by alexespejo — CHANGES_REQUESTED** [review]
Colors look good! Just nit pickings

**Comment by AureliaSindhu** [comment]
refactored the Settings Theme to use the MUI theme's read-only styling.

File: apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx (hunk 4 above)
Comment (alexespejo) [reply apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx]: still confused. how come there is a ternary here? `secondaryColor ?` will always evaluate to true right?

File: apps/antalmanac/src/hooks/useSecondaryColor.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
+import { useMemo } from 'react';
+
+import { BLUE } from '$src/globals';
+import { useThemeStore } from '$stores/SettingsStore';
+
+export function useSecondaryColor() {
+    const isDark = useThemeStore((store) => store.isDark);
+    const color = useMemo(() => (isDark ? '#90B3F9' : BLUE), [isDark]);
```
Comment (alexespejo) [inline apps/antalmanac/src/hooks/useSecondaryColor.ts]: use `LIGHT_BLUE`

**Review by alexespejo — CHANGES_REQUESTED** [review]
Sorry for slow reviews CS178 is evil ☹️

File: apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx (hunk 4 above)
Comment (alexespejo) [inline apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx]:
```suggestion
            <InputLabel variant="outlined" color={'secondary'}>
```

File: apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx [hunk 6]
```diff
@@ -19,13 +22,16 @@ export function ScheduleSelector({ scheduleIndices, onSelectScheduleIndices, sch
...
+                Select schedules
+            </InputLabel>
             <Select
                 variant="outlined"
                 label="Select schedules"
                 multiple
                 value={scheduleIndices}
                 onChange={handleChange}
+                color={secondaryColor ? 'secondary' : 'primary'}
```
Comment (alexespejo) [inline apps/antalmanac/src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx]:
```suggestion
                color={'secondary'}
```

**Review by alexespejo — CHANGES_REQUESTED** [review]
Will also ping Christy and Angela for further comments otherwise

**Comment by alexespejo** [comment]
@cubic

**Comment by alexespejo** [comment]
@cubic

**Review by alexespejo — CHANGES_REQUESTED** [review]
TODO:
Before starting: I noticed PeterPortal dialog buttons are white instead of our secondary color. Should we change that 

Image

Image

1. Consolidate the PeterPortal drop downs. Flip to a lighter gray and change the color buttons to primary

Image

2. Double check sign out colors. The user id textbox needs the secondary colorImage

3. Import dialog radio buttons and textbox 

Image

4. Patch notes close button

Image

5. Dialogs: I'm noticing that PeterPortal has dialogs that appear more like our prod dialogs with a lighter grey similar to the drop down comment
image

6. Loading bar on darkmode is black
image

**Comment by AureliaSindhu** [comment]
UPDATED CHANGES:
- unified dropdown for profile + switch to PP theme (same as old one)
Screenshot 2026-02-27 at 2 46 46 PM
Screenshot 2026-02-27 at 2 46 43 PM
- revise dark mode for help 
Screenshot 2026-02-27 at 3 38 35 PM

**Comment by AureliaSindhu** [comment]
updates: 
Screenshot 2026-02-28 at 1 24 02 PM
Screenshot 2026-02-28 at 1 24 06 PM
Screenshot 2026-02-28 at 1 24 13 PM
Screenshot 2026-02-28 at 1 24 36 PM

**Comment by AureliaSindhu** [comment]
@cubic

**Comment by AureliaSindhu** [comment]
@cubic

**Review by alexespejo — DISMISSED** [review]
LGTM! 🎨

**Comment by sicn4rf** [comment]
it looks like some of the menu item dropdowns in Manual search are still using the old color palette.

old:
image
 new:
image

**Comment by sicn4rf** [comment]
this might be a skill issue but
image

image

i feel like the contrast on the zebra striping is so much heavier on the new palette that is makes it quite difficult to discern whether a course is dimmed out signifying that it has a conflict with your current schedule, versus just the regular zebra striping.

these two screenshots are the exact same schedules, and i feel like they are not equally interpretable. or i could be like stupid

File: apps/antalmanac/src/components/Header/Signin.tsx [hunk 7]
```diff
@@ -197,7 +199,15 @@ export const Signin = () => {
                 loading={loadingSchedule}
             />
 
-            <Dialog open={isOpen} onClose={() => handleClose(true)}>
+            <Dialog
+                open={isOpen}
+                onClose={() => handleClose(true)}
+                PaperProps={{
+                    sx: {
+                        bgcolor: isDark ? '#383838' : 'background.paper',
```
Comment (sicn4rf) [inline apps/antalmanac/src/components/Header/Signin.tsx]: suggestion: this is the last hardcoded `#383838`, this should use the `DARK_PAPER_BG = '#383838';` defined in `globals.ts`

File: apps/antalmanac/src/components/Header/Signin.tsx [hunk 8]
```diff
@@ -285,23 +296,34 @@ export const Signin = () => {
...
+                        sx: getSettingsPopoverPaperSx(isDark),
                     },
                 }}
             >
                 <SettingsMenu user={null} onClose={() => setSettingsAnchorEl(null)} />
 
-                <Divider style={{ marginTop: '10px', marginBottom: '12px' }} />
+                <Divider style={{ marginTop: '20px', marginBottom: '12px' }} />
+
+                <MenuItem
```
Comment (sicn4rf) [inline apps/antalmanac/src/components/Header/Signin.tsx]: question: im confused about what this new item does? this doesnt seem related to the color palette pr. 

Image

it just takes me to "/" since im already on scheduler

**Comment by sicn4rf** [comment]
chore: the `usePrimaryColor` hook at `src/hooks/usePrimaryColor.ts` is no longer used anywhere since this pr replaced it with `useSecondaryColor`. it might be worth the clean up to avoid confusion

**Comment by sicn4rf** [comment]
overall this lgtm, most important thing to change is probably the menu dropdown

> it looks like some of the menu item dropdowns in Manual search are still using the old color palette.
> 
> old: image new: image

i just realized these both actually use the new palette but im not sure if their colors are intended to be different?

**Comment by AureliaSindhu** [comment]
@cubic

**Comment by sicn4rf** [comment]
image

it looks like the dimmed out overlay for the courses that conflict with your current schedule is completely indistinguishable from the zebra striping now. (or i think the dimmed overlay is just completely gone now)

**Comment by AureliaSindhu** [comment]
updated

**Comment by AureliaSindhu** [comment]
@cubic

**Comment by AureliaSindhu** [comment]
@cubic

**Review by alexespejo — DISMISSED** [review]
smoked

File: apps/antalmanac/src/app/Theme.tsx [hunk 9]
```diff
@@ -16,28 +16,52 @@ const roboto = Roboto({
...
+    settingsSegment: {
+        border: '#888888',
+        background: '#333333',
+        hoverBackground: '#424649',
     },
     background: {
-        default: '#303030',
-        paper: '#424242',
+        default: '#1E1E1E',
+        paper: '#1E1E1E',
```
Comment (sicn4rf) [inline apps/antalmanac/src/app/Theme.tsx]: isn't this supposed to be #2a2a2a? `background.paper` is set to #1E1E1E but later in this file (line 183) `MuiPaper.root` sets every components `backgroundColor` to `DARK_PAPER_BG` which is #2a2a2a. This means that `theme.palette.background.paper` doesn't reflect the actual rendered color of a `Paper` surface in dark mode. if all `Paper` surfaces should be #2a2a2a , then you should set `background.paper = DARK_PAPER_BG` and have the `MuiPaper.root` override reference `palette.background.color` instead of hardcoding `DARK_PAPER_BG`. that should make the palette consistent

File: apps/antalmanac/src/components/AlertDialog.tsx [hunk 10]
```diff
@@ -13,8 +14,21 @@ interface AlertDialogProps {
...
-        <Dialog open={open} onClose={onClose}>
-            <DialogContent sx={{ fontSize: 'small' }}>
+        <Dialog
+            open={open}
+            onClose={onClose}
+            PaperProps={{
+                sx: {
+                    ...(isDark && { bgcolor: DARK_PAPER_BG, color: 'text.primary' }),
+                },
+            }}
```
Comment (sicn4rf) [inline apps/antalmanac/src/components/AlertDialog.tsx]: now that `darkPaperOverride` is applied to all `MuiPaper.root` globally thru `Theme.tsx`, that makes these in component overrides redundant. Dialog renders as Paper, so the global override should already handle the dark background and text color. i notice this same pattern in `Signin.tsx` line 204, `ScheduleSelect.tsx` line 319, `NotificationTabs.tsx` line 164, and `NotificationsTable.tsx` line 128. all five should prob be cleaned up.

theyre not causing any bugs right now but they create a maintenance trap for the future. if a dev in the future will look at `AlertDialog` and see that the component explicitly needs special dark styling, they wont know if its safe to remove. it also makes the global override feel unreliable bc why are we doing in-component overrides if the global override already did it?

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/SearchForm.tsx
Comment (sicn4rf) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/SearchForm.tsx]: are we purposely still using `DODGER_BLUE` here or was this missed? should it be `alpha(LIGHT_BLUE, 0.05)` or `alpha(theme.palette.secondary.main, 0.05)` to stay consistent with the selected indicator color ? not rlly a big deal cuz its just the little tint when you select manual or quick search. feel free to dismiss

File: apps/antalmanac/src/components/Calendar/Toolbar/CalendarToolbar.tsx [hunk 11]
```diff
@@ -163,9 +163,17 @@ export const CalendarToolbar = memo((props: CalendarPaneToolbarProps) => {
...
                                 borderRadius: '4px',
                                 padding: '3px',
+                                ...(showFinalsSchedule &&
+                                    theme.palette.mode === 'dark' && {
+                                        backgroundColor: 'primary.main',
+                                        color: '#fff',
+                                        '&:hover': {
+                                            backgroundColor: 'primary.dark',
+                                        },
+                                    }),
```
Comment (sicn4rf) [inline apps/antalmanac/src/components/Calendar/Toolbar/CalendarToolbar.tsx:176]: small inconsistency in this block: you use both `theme.palette.primary.main` and `'primary.main'` / `'primary.dark'`. both work in this context but mixing them up in the same block is pretty inconsistent, i'd suggest using `theme.palette.primary.main` and `theme.palette.primary.dark` instead

File: apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx [hunk 12]
```diff
@@ -4,13 +4,16 @@ import { Fragment, useCallback, useMemo, useState } from 'react';
...
+import { BLUE, LIGHT_BLUE } from '$src/globals';
+import { useThemeStore } from '$stores/SettingsStore';
 
 interface RestrictionsCellProps {
     restrictions: string;
 }
 
 export const RestrictionsCell = ({ restrictions }: RestrictionsCellProps) => {
     const isMobile = useIsMobile();
+    const isDark = useThemeStore((store) => store.isDark);
```
Comment (sicn4rf) [inline apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx]: isnt this the same pattern that was implemented in the `useSecondaryColor()` hook in `useSecondaryColor.ts`? i notice this same pattern in `GpaCell.tsx` and `CustomInputBox.tsx` where it was used correctly.

**Review by sicn4rf — CHANGES_REQUESTED** [review]

**Review by sicn4rf — APPROVED** [review]
this lgtm !! after tons of iterations, i think this palette looks solid and should be easier to adjust in the future if we ever decide to change it again. 👍 
Image
approved

**Review by alexespejo — APPROVED** [review]

**Review by alexespejo — APPROVED** [review]
