### PR TITLE
Fix overlapping dashed lines. Overlapping pins now stack.

### LINKED ISSUE #169: Map pins don't indicate when multiple classes are in one building
### Problem
When a student has 2+ classes in the same building, the map does not reflect that. Currently it only shows the color of the first class. 

### Screenshot
image

### Objective
Find a good way to indicate that a user has multiple classes in the building. 

### Ideas
- Show both colors on the pin
- Put 2 pins next to each other
- On hover, show a popup

### Related
PR #168 adds numbers to the pins to represent the order of classes in the schedule. Maybe we could do something with the pin number to show multiple classes are in that building?

### PR DESCRIPTION
**Pull request by falsidge**
## Summary
Fix dashed lines having different colors than the solid lines.

Pins now stack on top of each other.

image

Old
image

## Test Plan
Checked pins on all days. Tested 5 pins stacked on one building.

## Issues
#169 

#112 also exists and may conflict with this

## Future Followup (Optional)
Future ideas

One popup for the entire stack?
Add time of courses to popup

### CODE REVIEW

**Comment by ChaseC99** [comment]
I think this is a brilliant way to handle this!! Tested the changes locally and it looks awesome 👌 
I'll take some time to actually review the code this week.

**Comment by ChaseC99** [comment]
> #112 also exists and may conflict with this

I don't think they really conflict. To add an image carousel, we would just be updating the existing `MapMarkerPopup` component. But I think this overlapping pins feature is way more important than the carousel anyways.

File: client/src/components/Map/UCIMap.js [hunk 1]
```diff
@@ -232,28 +246,41 @@ export default class UCIMap extends PureComponent {
...
                     !(
-                        event.isCustomEvent ||
-                        !event.scheduleIndices.includes(AppStore.getCurrentScheduleIndex()) ||
-                        !event.start.toString().includes(DAYS[this.state.day])
+                        (
+                            event.isCustomEvent ||
+                            !event.scheduleIndices.includes(AppStore.getCurrentScheduleIndex()) ||
+                            !event.start.toString().includes(DAYS[this.state.day]) ||
+                            courses.has(event.sectionCode) || // Remove duplicate courses that appear in the calendar
+                            !courses.add(event.sectionCode)
```
Comment (ChaseC99) [inline client/src/components/Map/UCIMap.js:262]: Won't this always return true, since the set isn't empty?

**Review by ChaseC99 — APPROVED** [review]
Looks awesome 👍  
Always so impressed with your work on the map component!

File: client/src/components/Map/UCIMap.js (hunk 1 above)
Comment (falsidge) [reply client/src/components/Map/UCIMap.js:262]: it's a trick and I think it might not be very clear but I couldn't think of an easier way to add filtering of the sectioncode without going through the array again at the time.
if !event.scheduleIndices.includes(AppStore.getCurrentScheduleIndex()) or !event.start.toString().includes(DAYS[this.state.day]) conditions are true then it is negated and returns false to the filter (if the schedule indices does not include the current index or the event does not start in the current day). If those are passed, check if the courses set if the event has already been added, if true it return false after negation and filter skips it else it adds to the set and return false, which actually returns true.

a better way to handle this is to "Use addedCourses instead of eventsInCalendar to create markers"  as #112 mentioned
