### PR TITLE
fix: switcher layout shift

### LINKED ISSUE #1503: Planner Button Bug
## Description
After adding classes onto my AntAlmanc page and then clicking the planner button, I'm prompted that I have unsaved changes. Once I go ahead and save it and I get the confirmation toast that it's saved and I click on the planner button it won't let me switch to the planner page.  

## Steps to Recreate
1. Add a class to your schedule 
2. Click on the planner button
3. Once prompted that you have unsaved changes, go ahead and press the save button 
4. Click the planner button 

The behavior that's observed is that I'm not able to switch onto the page.

### PR DESCRIPTION
**Pull request by dsnsgithub**
## Summary

Fixes layout shift and persistent loading animation when there are unsaved changes and the user is moving between scheduler and planner.

Planner should mirror these changes.

https://github.com/user-attachments/assets/e2ca208a-42e7-421c-b833-9bc108a5824e

## Test Plan

After adding a section, navigating to planner, and activating unsaved changes:

- the loading animation is cancelled if the user decides to make changes
- there is no layout shift

## Issues

Closes #1503

Successor to https://github.com/icssc/AntAlmanac/pull/1548 (adds loading spinner, moves switcher to separate component to mirror https://github.com/icssc/AntAlmanac/pull/1509)

### CODE REVIEW

**Review by victorialee13 — DISMISSED** [review]
lgtm

File: apps/antalmanac/src/components/Header/AppSwitcher.tsx [hunk 1]
```diff
@@ -11,10 +11,11 @@ import {
...
 } from '@mui/material';
 import { useState } from 'react';
+import type { MouseEventHandler } from 'react';
 
 import { Logo } from '$components/Header/Logo';
-import { BLUE } from '$src/globals';
-
+import { BLUE, PLANNER_LINK } from '$src/globals';
+import appStore from '$stores/AppStore';
 type AppSwitcherProps = {
```
Comment (Choollol) [inline apps/antalmanac/src/components/Header/AppSwitcher.tsx:20]: Tiny nitpick: Add a line of whitespace between imports above and this type declaration

File: apps/antalmanac/src/components/Header/AppSwitcher.tsx [hunk 2]
```diff
@@ -25,12 +26,28 @@ export function AppSwitcher({ isMobile }: AppSwitcherProps) {
...
+
+            // user chose to leave, suppress beforeunload warning
+            appStore.unsavedChanges = false;
+        }
+
         setPlannerLoading(true);
     };
 
-    const plannerIcon = plannerLoading ? <CircularProgress size={16} color="inherit" /> : <Route />;
+    const plannerIcon = plannerLoading ? <CircularProgress size={20} sx={{ margin: 0 }} color="inherit" /> : <Route />;
```
Comment (Choollol) [inline apps/antalmanac/src/components/Header/AppSwitcher.tsx]: Could you explain what the `margin: 0` is for? It looked the same without the `sx` prop in my own testing, but I might be missing something.

**Review by Choollol — CHANGES_REQUESTED** [review]

File: apps/antalmanac/src/components/Header/AppSwitcher.tsx (hunk 2 above)
Comment (dsnsgithub) [reply apps/antalmanac/src/components/Header/AppSwitcher.tsx]: I was testing different layout shift fixes and it isn't needed anymore. Nice catch.

**Review by Choollol — APPROVED** [review]
lgtm!
