### PR TITLE
fix: restriction pop up on mobile

### LINKED ISSUE #1154: Restrictions pop-over for mobile
## Description
- On desktop, hovering over the restriction code lets you see the pop-over, and clicking it takes you to the University's page, which makes sense.
- However, since we can't hover on mobile, the user can't see the pop-over, which is probably what they'd want to see if they clicked on the restriction code.

### PR DESCRIPTION
**Pull request by AureliaSindhu**
## Summary
Added mobile support for restriction code popovers in RestrictionsCell. On mobile, clicking a restriction code opens a Popover with descriptions and a "University Requirements" link, since hover isn't available.
Screenshot 2026-01-06 at 3 02 53 PM

## Test Plan
Use mobile view and click on restrictions for a chosen class. 

## Issues

Closes #1154

### CODE REVIEW

**Comment by KevinWu098** [comment]
Deferring review over to @alexespejo 🫡

File: apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx [hunk 1]
```diff
@@ -23,20 +27,85 @@ export const RestrictionsCell = ({ restrictions }: RestrictionsCellProps) => {
...
+    const restrictionDescriptions = <Typography>{parseRestrictions(restrictions)}</Typography>;
+
+    const restrictionContent = (
+        <Box
+            sx={{
+                display: 'block',
+                padding: 1,
+            }}
+        >
+            <Typography>{parseRestrictions(restrictions)}</Typography>
```
[the remark this answers is not in the document]
Comment (alexespejo) [reply apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx]: what he said ^

[the remark this answers is not in the document]
Comment (AureliaSindhu) [reply apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx]: done!

File: apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx [hunk 2]
```diff
@@ -23,20 +27,85 @@ export const RestrictionsCell = ({ restrictions }: RestrictionsCellProps) => {
...
+            <Typography
+                component="a"
+                href="https://www.reg.uci.edu/enrollment/restrict_codes.html"
+                target="_blank"
+                rel="noopener noreferrer"
+                sx={{
+                    textDecoration: 'underline',
```
Comment (alexespejo) [inline apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx]: chore: since it's an anchor tag the `textDecoration` and `color` change seem redundant

File: apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx [hunk 3]
```diff
@@ -23,20 +27,85 @@ export const RestrictionsCell = ({ restrictions }: RestrictionsCellProps) => {
...
                             target="_blank"
                             rel="noopener noreferrer"
+                            onClick={handleClick}
+                            sx={{ cursor: 'pointer' }}
                         >
                             {restrictions}
-                        </a>
-                    </Typography>
-                </Tooltip>
+                        </Typography>
```
[the remark this answers is not in the document]
Comment (alexespejo) [reply apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx:81]: this is kinda troll that my review is just what the copilot said lol. 

chore: seems like you're repurposing the anchor tag to create the styling for the button. It's clever but a little hacky even though it's a small snippet it's better practice to just mimic the styling with the css classes and make it a button. somn like that correct me if I'm wrong

File: apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx [hunk 4]
```diff
@@ -23,20 +27,85 @@ export const RestrictionsCell = ({ restrictions }: RestrictionsCellProps) => {
...
+                            onClose={handleClose}
+                            anchorEl={anchorEl}
+                            anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }}
+                        >
+                            {restrictionContent}
+                        </Popover>
+                    </>
+                ) : (
+                    <Tooltip title={restrictionDescriptions}>
+                        <Typography>
```
Comment (alexespejo) [inline apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx]: chore: consistency change to use the ` component="a"` prop (`<Typogrophy   component="a">`)

**Review by alexespejo — CHANGES_REQUESTED** [review]
smol changes

File: apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx [hunk 5]
```diff
@@ -1,42 +1,106 @@
...
+                return null;
+            }),
+        [restrictions]
+    );
+
+    const handleClose = useCallback(() => {
+        setAnchorEl(null);
+    }, []);
+
+    const restrictionDescriptions = <Typography>{parsedRestrictions}</Typography>;
```
Comment (alexespejo) [inline apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx:36]: question: is there a reason you pass the <Typography> component to line 45 instead of just `parsedRestrictions`

**Review by alexespejo — CHANGES_REQUESTED** [review]
one smol question and I'll approve after

File: apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx (hunk 5 above)
Comment (AureliaSindhu) [reply apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/RestrictionsCell.tsx:36]: it was just for consistent styling in the Tooltip, though `parsedRestrictions` could work directly. Would you like me to just use the `paredRestrictions` directly?

**Review by alexespejo — APPROVED** [review]
MTGL!
