### PR TITLE
Fix: capitals in FuzzySearch queries

### LINKED ISSUE #733: Capitals in Fuzzy Search Fail
## Potential Solution
To also support capitals in the Fuzzy Search query, we can quietly set the passed query to lowercase, thereby making sure it'll work with Fuzzy Search.

Make sure that any potential fix is appropriately tested! Handling the query differently may also require additional changes elsewhere in `FuzzySearch.tsx`!

## Screenshots of Bug
All-Caps (also with any combination of upper + lower)
Screenshot 2023-10-13 at 4 01 54 PM

Lowercase
Screenshot 2023-10-13 at 4 02 30 PM

## Misc
Alternatively, update the fuzzy-search package, but let's not break Eddy's back

### PR DESCRIPTION
**Pull request by pinapelz**
## Summary
Fixes capitals in FuzzySearch queries by changing all passed queries to lowercase

image

## Issues

Closes #733

### CODE REVIEW

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/FuzzySearch.tsx [hunk 1]
```diff
@@ -64,13 +64,15 @@ class FuzzySearch extends PureComponent<FuzzySearchProps, FuzzySearchState> {
...
                 if (!deptLabel) {
                     const deptSearch = search({ query: deptValue.toLowerCase(), numResults: 1 });
-                    deptLabel = deptSearch[deptValue].name;
-                    this.setState({
-                        cache: {
-                            ...this.state.cache,
-                            [deptValue.toLowerCase()]: deptSearch,
-                        },
-                    });
+                    if (deptSearch[deptValue]) {
```
Comment (EricPedley) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/FuzzySearch.tsx:67]: Does it break if we don't have this here or something? Just curious why you added this.

**Review by EricPedley — CHANGES_REQUESTED** [review]
Almost LGTM, just one question to answer.

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/FuzzySearch.tsx (hunk 1 above)
Comment (pinapelz) [reply apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/FuzzySearch.tsx:67]: It does, for whatever reason `deptSearch[deptValue]` ends up not being ready.
Screenshot_20231023_023300

**Review by EricPedley — APPROVED** [review]
