### PR TITLE
fix: stop loading on browser back navigation

### LINKED ISSUE #1575: Planner loading spinner breaks on browser back navigation
## Steps to recreate
1. Go to https://antalmanac.com/ and _wait several seconds for everything to load_
2. Click the Planner button in the navbar
3. Use the browser back navigation

You will see that the Planner button is still disabled and shown as loading. It is now impossible to use until reloading the page
Image

## Intended behavior
Loading should stop if the page is reopened

### PR DESCRIPTION
**Pull request by dsnsgithub**
## Summary
The Planner button should no longer have a loading animation or be disabled when using the browser back button.

## Test Plan
This bug only occurs in staging/production and is difficult to replicate in a development environment.

Running
```
pnpm run --filter antalmanac build
pnpm run --filter antalmanac start
```
will allow bfcache to work.

This PR can also be compared to other staging instances.

## Issues

Closes https://github.com/icssc/AntAlmanac/issues/1575

### CODE REVIEW

File: apps/antalmanac/src/components/Header/AppSwitcher.tsx [hunk 1]
```diff
@@ -63,6 +63,15 @@ export function AppSwitcher({ isMobile }: AppSwitcherProps) {
         setPlannerLoading(true);
     };
 
+    useEffect(() => {
+        const handlePageShow = (event: PageTransitionEvent) => {
+            if (event.persisted) setPlannerLoading(false);
```
Comment (Choollol) [inline apps/antalmanac/src/components/Header/AppSwitcher.tsx]: Formatting nitpick
```suggestion
            if (event.persisted) {
                setPlannerLoading(false);
            }
```

**Review by Choollol — CHANGES_REQUESTED** [review]
LGTM, just a small formatting thing.

**Review by Choollol — APPROVED** [review]
LGTM
