### PR TITLE
Fix issues related to console errors and deprecated code

### LINKED ISSUE #1506: Fix issues related to console errors and deprecated code
There are a couple errors and a lot of warnings about deprecated code. We should fix this so the console during development is cleaner and things don't break in the future.

### PR DESCRIPTION
**Pull request by Choollol**
## Test Plan

Ensure console errors are gone and warnings related to deprecated code are gone too.

Also ensure features aren't broken:
1. Recruitment console should show correctly
2. Calendar event popovers and hovering courses should work correctly
3. Save and sign in buttons should work and show loading states correctly
4. The logo should be unchanged

## Issues

Closes #1506

### CODE REVIEW

File: apps/antalmanac/src/components/Header/Save.tsx [hunk 1]
```diff
@@ -47,6 +46,7 @@ export const Save = () => {
             });
             setSaving(true);
             await saveSchedule(accounts.providerAccountId, true, users);
+            await new Promise((res) => setTimeout(res, 5000));
```
Comment (alexespejo) [inline apps/antalmanac/src/components/Header/Save.tsx]: question: what's this for?

Comment (Choollol) [reply apps/antalmanac/src/components/Header/Save.tsx]: oopsie left over from testing thanks for catching it

**Review by alexespejo — DISMISSED** [review]
LGTM

**Review by alexespejo — APPROVED** [review]
