### PR TITLE
Fix Course Color Bug

### LINKED ISSUE #196: Changing Color is Broken
Trying to change a course color from the schedule pane or added classes pane causes the site to crash.
I believe this is because `componentDidUpdate` is changing the state and causing infinite recursion.
color_bug

### PR DESCRIPTION
**Pull request by ChaseC99**
## Summary
Calendar events show the correct color for the color picker.

## Test Plan
- Load a schedule with courses and custom events
- Change the color of courses and custom events
- Change the color from the "Added Classes" section
- Verify that the courses change color and that the color picker is correctly reset on each new event
color_bug_fix

## Issues
Closes #196

### CODE REVIEW

File: client/src/components/Calendar/ScheduleCalendar.js [hunk 1]
```diff
@@ -183,8 +184,13 @@ class ScheduleCalendar extends PureComponent {
         const { currentTarget } = event;
         event.stopPropagation();
 
-        if (courseInMoreInfo.sectionType !== 'Fin')
-            this.setState({ anchorEvent: currentTarget, courseInMoreInfo: courseInMoreInfo });
+        if (courseInMoreInfo.sectionType !== 'Fin') {
+            this.setState({
+                anchorEvent: currentTarget,
+                courseInMoreInfo: courseInMoreInfo,
+                calendarEventKey: Math.random(),
```
Comment (ChaseC99) [inline client/src/components/Calendar/ScheduleCalendar.js:191]: Update the `calendarEventKey` to a random number onClick to force a re-render for `CourseCalendarEvent`

File: client/src/components/Calendar/ScheduleCalendar.js [hunk 2]
```diff
@@ -242,6 +248,7 @@ class ScheduleCalendar extends PureComponent {
                         open={Boolean(this.state.anchorEvent)}
                     >
                         <CourseCalendarEvent
+                            key={this.state.calendarEventKey}
```
Comment (ChaseC99) [inline client/src/components/Calendar/ScheduleCalendar.js:251]: `CourseCalendarEvent` wasn't fully re-rendering, which is why the colors didn't update. By changing the key, we guarantee a full re-render.

File: client/src/components/App/ColorPicker.js [hunk 3]
```diff
@@ -32,7 +32,9 @@ class ColorPicker extends PureComponent {
             if (this.props.isCustomEvent) changeCustomEventColor(this.props.customEventID, this.state.color);
             else changeCourseColor(this.props.sectionCode, this.state.color, this.props.term);
         });
+    };
 
+    handleColorChangeComplete = () => {
```
Comment (ChaseC99) [inline client/src/components/App/ColorPicker.js:37]: Move GA event to new `handleColorChangeComplete` function.  onChange is triggered many times while a user is dragging the color picker around. GA was firing analytics for this, messing up our numbers. By moving it into the onChangeComplete callback, we fix this bug.
