### PR TITLE
Fix/dev mirror deploymnet

### LINKED ISSUE #1272: Fix development mirror deployment
### Solution 
- Temporarily always deploy the staging backend (#1273).
  - This breaks local auth.
- Permanent fix: have the *dev* backend create new oAuth clients that redirect to the URLs requested by the frontend.
  - A singleton (e.g., `GoogleOAuth2ClientsManager`) lazily creates and returns clients, allowing for the wildcard if `STAGE=='dev'`. 
  - IMPORTANT: This must be validated to make sure that the redirect follows `staging-{PR}.antalmanac.com/auth` so as not to be a security vulnerability. Be very careful.
  - The client should only be allowed to send a 4-digit number that we slot into the PR number. 

### Discussion
- The development mirror has not been working since the auth merge.
- The error is missing env vars related to Google Auth. However, the problem is that staging instances need to be redirected to different places, which is currently not possible.
- Therefore, the two alternatives are:
  1) Give every staging instance its own backend. As far as I see, this shouldn't incur noticeable compute costs. However, this means that each PR will need to be added to the Google Auth console.
  2) Have an auth micro-service shared between prod and staging.
- I'm inclined to go with the first because it's simpler. 

CC: @KevinWu098 and @alexanderl19

### PR DESCRIPTION
**Pull request by alexespejo**
## Summary
Creates a Google OAuth class to dynamically change the Redirect URI

## Issues
- Still requires us to manually whitelist every staging URL for testing

Closes #1272

### CODE REVIEW

File: apps/backend/src/lib/googleOAuth.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
+import { URL } from 'url';
+import { OAuth2Client } from 'google-auth-library';
+import { backendEnvSchema } from 'src/env';
+import { TRPCError } from '@trpc/server';
+
+export class GoogleOAuth2ClientsManager {
```
Comment (MinhxNguyen7) [inline apps/backend/src/lib/googleOAuth.ts:10]: Have a short docstring what this class does.

File: apps/backend/src/lib/googleOAuth.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+    constructor(_clientId: string, _clientSecret: string) {
+        this.clientId = _clientId;
+        this.clientSecret = _clientSecret;
+
+        const { STAGE, GOOGLE_REDIRECT_URI } = backendEnvSchema.parse(process.env);
+        this.allowDynamicRedirects = STAGE !== 'prod';
+        this.redirectOrigin = GOOGLE_REDIRECT_URI;
+    }
+
+    getClient(redirectOrigin: string): OAuth2Client {
```
Comment (MinhxNguyen7) [inline apps/backend/src/lib/googleOAuth.ts:35]: A docstring here, including what the important conditions are, would be good, too

**Review by MinhxNguyen7 — CHANGES_REQUESTED** [review]
See above

**Review by MinhxNguyen7 — APPROVED** [review]
Let's see
