### PR TITLE
fix: search redesign pt 2

### LINKED ISSUE #1290: Refactor and Refine Search
## Description
- #1275 is a major improvement to search, but there are areas of improvement that we must address.

## TODO
- [ ] Enumerate refactoring and refinement tasks, including comments from #1275.
- [ ] TBA

### PR DESCRIPTION
**Pull request by xgraceyan**
## Summary
Aims to fix implementation issues with original search redesign #1275, along with several other shortcomings of the manual search design in general
- New labelled input components now simply combine a separate label with the input instead of using InputAdornment
- Advanced search fields are more organized
- Multiselect is now displayed as a checkbox select
- Proper time pickers for start and end time instead of selecting individual times
image

## Test Plan
- [ ] Ensure text, select, multiselect, time picker, and autocomplete fields are functional
- [ ] Ensure labels are associated with their proper fields
- [ ] Ensure there are no UI bugs with inputs, icons, mobile view

## Issues

Closes #1290

### CODE REVIEW

**Comment by KevinWu098** [comment]
Thanks for working on this, especially over the summer! 

Some quick notes as I'm on mobile and can't currently reveal in detail:

1. It looks like you didn't start this branch off of the most recent commit in main? I think you may want to merge in main to your branch so that the diff is accurate to the current state
2. There's no staging deployment (because you have merge conflicts). Could you look into that?

**Comment by MinhxNguyen7** [comment]
Very cool

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledSelect.tsx [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    label,
+    selectProps,
+    children,
+    isAligned,
+}: LabelledSelectProps<T>) {
+    const id = useId();
+
+    return (
+        <LabelledInput label={label} isAligned={isAligned} id={id}>
+            <Select size="small" variant="outlined" inputProps={{ id }} {...selectProps}>
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledSelect.tsx]:
```suggestion
            <Select size="small" variant="outlined" inputProps={{ id }} MenuProps={{
                    marginThreshold: null,
                }} {...selectProps}>
```

suggestion: adding this prop will make the input field never render _above_ the select element

https://github.com/mui/material-ui/issues/36776#issuecomment-1698892977

### Before
Image

### After (this is on #1295)
Image

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx [hunk 2]
```diff
@@ -126,242 +127,210 @@ export function AdvancedSearchTextFields() {
...
         <Box
+            display={'flex'}
+            flexWrap={'wrap'}
+            gap={2}
             sx={{
-                display: 'flex',
-                gap: 2,
-                flexWrap: 'wrap',
                 marginBottom: '1rem',
             }}
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx]: nit: while not wrong, we try to place props into `sx` whenever possible

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx [hunk 3]
```diff
@@ -126,242 +127,210 @@ export function AdvancedSearchTextFields() {
...
-                        onChange: changeHandlerFactory('coursesFull'),
-                    }}
-                >
-                    <MenuItem value={'ANY'}>Include all classes</MenuItem>
-                    <MenuItem value={'SkipFullWaitlist'}>Include full courses if space on waitlist</MenuItem>
-                    <MenuItem value={'SkipFull'}>Skip full courses</MenuItem>
-                    <MenuItem value={'FullOnly'}>Show only full or waitlisted courses</MenuItem>
-                    <MenuItem value={'Overenrolled'}>Show only over-enrolled courses</MenuItem>
-                </AdornedSelect>
+            <Box display={'flex'} flexWrap={'wrap'} gap={2} width={'100%'}>
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx]: nit: sx

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx [hunk 4]
```diff
@@ -126,242 +127,210 @@ export function AdvancedSearchTextFields() {
...
+                            value: units,
+                            onChange: changeHandlerFactory('units'),
+                            type: 'search',
+                            id: 'units',
+                            placeholder: 'ex. 3, 4, or VAR',
+                            fullWidth: true,
+                        }}
+                    />
+                </Box>
+                <Box flex={1}>
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx]: question: what does this Box with `flex={1}` actually do? if we removed it, what would happen?

question: if every field needs Box `flex={1}`, that feels like a smell and we should probably just apply the styling on the component itself?

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx [hunk 5]
```diff
@@ -126,242 +127,210 @@ export function AdvancedSearchTextFields() {
...
-                    label="Course Level"
-                    selectProps={{
-                        value: division,
-                        onChange: changeHandlerFactory('division'),
-                        displayEmpty: true,
-                        MenuProps: {
-                            anchorOrigin: {
-                                vertical: 'bottom',
-                                horizontal: 'left',
+            <Box display={'flex'} flexWrap={'wrap'} gap={2} width={'100%'}>
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx]: nit: sx

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx [hunk 6]
```diff
@@ -126,242 +127,210 @@ export function AdvancedSearchTextFields() {
...
+                            },
+                        }}
+                    >
+                        {EXCLUDE_RESTRICTION_CODES_OPTIONS.map((option) => (
+                            <MenuItem key={option.value} value={option.value} sx={{ paddingY: 0.25 }}>
+                                <Checkbox
+                                    checked={excludeRestrictionCodes.includes(option.value)}
+                                    inputProps={{ 'aria-labelledby': `option-label-${option.value}` }}
+                                />
+                                <ListItemText id={`option-label-${option.value}`} primary={option.label} />
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/AdvancedSearch/AdvancedSearchTextFields.tsx]: 🔥 great

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/CustomInputLabel.tsx [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+            sx={{
+                display: 'flex',
+                alignItems: 'center',
+                height: '34.25px',
+                px: 1.5,
+                minWidth: isAligned ? '10.35rem' : '6rem',
+                bgcolor: isDark ? grey[800] : grey[200],
+                whiteSpace: 'nowrap',
+                border: '1px solid',
+                borderColor: isDark ? 'rgba(255, 255, 255, 0.23)' : 'rgba(0, 0, 0, 0.23)',
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/CustomInputLabel.tsx:28]: suggestion: when you have very specific values (34.25px, 10.35rem, 0.23 transparency), you should explain why those values are what they are

follow-up question: why are the values what they are? the height in particular smells like something that could be prone to flakiness.

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledAutocomplete.tsx [hunk 8]
```diff
@@ -0,0 +1,51 @@
+import { Autocomplete, AutocompleteProps, TextFieldProps } from '@mui/material';
+import { useId } from 'react';
+
+import { LabelledTextField } from '$components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledTextField';
+
+interface LabelledAutocompleteProps<
+    T,
+    Multiple extends boolean = false,
+    DisableClearable extends boolean = false,
+    FreeSolo extends boolean = false,
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledAutocomplete.tsx]: question: what... is this?

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledTimePicker.tsx [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+import { LabelledTextField } from '$components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledTextField';
+import { useThemeStore } from '$stores/SettingsStore';
+
+interface LabelledTimePickerProps {
+    label: string;
+    textFieldProps?: TextFieldProps;
+    isAligned?: boolean;
+}
+
+export const LabelledTimePicker = ({ label, textFieldProps, isAligned }: LabelledTimePickerProps) => {
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledTimePicker.tsx]: question: can we make the time picker work in increments of 30 minutes only? since courses don't start at random minutes. I think MUI should provide something for it?

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/ManualSearch.tsx [hunk 10]
```diff
@@ -13,29 +13,29 @@ interface ManualSearchProps {
 
 export function ManualSearch({ onSubmit, onReset }: ManualSearchProps) {
     return (
-        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5 }}>
-            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
-                <Box sx={{ display: 'flex', width: '100%', gap: 2, flexWrap: 'wrap' }}>
+        <Box display="flex" flexDirection="column" gap={0.5}>
+            <Box display="flex" flexDirection="column" gap={2}>
+                <Box display="flex" width="100%" gap={2} flexWrap={'wrap'}>
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/ManualSearch.tsx]: nit: sx

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/ManualSearch.tsx [hunk 11]
```diff
@@ -13,29 +13,29 @@ interface ManualSearchProps {
...
                     <Box sx={{ flex: 1 }}>
                         <DepartmentSearchBar />
                     </Box>
                     <Box sx={{ flex: 1 }}>
                         <CourseNumberSearchBar />
                     </Box>
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/ManualSearch.tsx]: repeat: why does everything have a box with flex one?

**Review by KevinWu098 — CHANGES_REQUESTED** [review]
Pretty great PR, thanks for working this over the summer! Most comments are on improvements that I can think of, but I don't see anything majorly blocking this PR :)

Once again, really solid work! I'm going to CC @jotalis for an extra pair of eyes, if he'd like to review

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/CustomInputLabel.tsx (hunk 7 above)
Comment (jotalis) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/CustomInputLabel.tsx]: issue: the height is flaky on larger resolutions. note the height difference of the label (34.25px) and input (40px) box below

image

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/CustomInputLabel.tsx [hunk 12]
```diff
@@ -0,0 +1,39 @@
...
+    return (
+        <InputLabel
+            htmlFor={id}
+            shrink={false}
+            sx={{
+                display: 'flex',
+                alignItems: 'center',
+                height: '34.25px',
+                px: 1.5,
+                minWidth: isAligned ? '10.35rem' : '6rem',
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/CustomInputLabel.tsx]: suggestion: when you have very specific values (34.25px, 10.35rem, 0.23 transparency), you should explain why those values are what they are

follow-up question: why are the values what they are? the height in particular smells like something that could be prone to flakiness.

**Review by jotalis — DISMISSED** [review]
Solid PR! Thanks for taking the time to address the things we talked about.

I had some of the same questions that Kevin brought up in his review, but aside from that and one visual issue, the code overall looks good.

Only small nit would be preferring the single-'L' "Labeled" over "Labelled"  as it's the conventional for American english e.g., `LabelledSelect` => `LabeledSelect`, `LabelledTextField` => `LabeledTextField`

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledAutocomplete.tsx (hunk 8 above)
Comment (xgraceyan) [reply apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/LabelledInputs/LabelledAutocomplete.tsx]: Autocomplete props needs like 4 required type arguments, which are those

**Review by KevinWu098 — APPROVED** [review]
LGTM :)

File: apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/ManualSearch.tsx [hunk 13]
```diff
@@ -13,29 +13,55 @@ interface ManualSearchProps {
...
-                    <Box sx={{ flex: 1 }}>
-                        <CourseNumberSearchBar />
-                    </Box>
+        <Box
+            sx={{
+                display: 'flex',
+                flexDirection: 'column',
+                gap: 0.5,
+            }}
+        >
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/CoursePane/SearchForm/ManualSearch.tsx:22]: test
