### PR TITLE
style: fix antalmanac MUI stylings (and UX)

### LINKED ISSUE #1073: RFC: Refactor Enrollment & Grade Distribution Popovers to Modals
Having these large charts render on hover feels incorrect -- when moving across search results, these popovers often appear when unwanted (simply because the mouse ends up moving over it on scroll)

Moving to use modals, on click, would allow for larger charts, and possibly more detail (especially on mobile)

IIRC, the original intent for onHover was for ease of access, but I believe users would prefer an explicit opt-in (i.r. clicking)

### PR DESCRIPTION
**Pull request by KevinWu098**
## Context
AntAlmanac has a few styling (and UX) issues that noticeably degrade the user experience. This PR is (hopefully) the first of a few PRs aiming to finally bring AA to MUI v5 (though v6 is out now...) and to resolve many problems littering the codebase (e.g. mobile breakpoints).

A few of the larger problems are detailed below:

### Unreadable primary colors on dark mode
<p align="center">

<br/>
What does the blue text even say?
</p>

### Computationally expensive, visually blocking elements `onHover`
<p align="center">

<br/>
A considerable amount of time is wasted moving the mouse off of an unwanted hover
</p>

## Summary
In terms of LOC, this PR is not particularly big but it does touch most parts of our UI.

A (mostly comprehensive, but probably non-exhaustive) list of changes are listed here:

1. Adds `src/` as an alias (e.g. `../../**/globals` -> `$src/globals`)
2. Refactors `Header`
3. Restyles `RecruitmentBanner`
4. Converted `CourseInfoButton` into an `onClick` button, rather than `onHover`

chrome-capture-2025-0-30

5. Added `BLUE` (#305db7, darker) and `DODGER_BLUE` (#1e90ff, lighter) as globals
6. Made course info buttons always `BLUE`
7. Made clickable text (e.g. link text, MapLink, GPA Cell) `BLUE` on dark mode and `DODGER_BLUE` on light mode
8. Set Split to always be `BLUE` and fixed dot centering
9. Dark mode's primary color is now `DODGER_BLUE` (most noticeable in tab indicators, inputs, selects)
10. Updated `Theme` and `ThemeV5` to be virtually identical (will eventually get rid of `Theme`)
11. Added overrides to fix dialogs (left is new)

Screenshot 2025-01-30 at 10 22 02 PM

## Test Plan
There are no logic changes here, so it's somewhat hard to give a step-by-step, as many of our PRs do for their test plans. 

My recommendation is to quite literally attempt every flow within AntAlmanac that you can imagine, on both light and dark.

A (non-exhaustive) checklist might be:
- [ ] Search page (filters, searching)
- [ ] Search results page (adding courses, removing courses, GPA button, link buttons (e.g. MapLink), course info buttons)
- [ ] Added page
- [ ] Map page (tabs, days, markers)
- [ ] Header
- [ ] Settings Drawer
- [ ] Calendar

## Closes
#1073

### CODE REVIEW

File: apps/antalmanac/src/components/Header/Header.tsx [hunk 1]
```diff
@@ -1,53 +1,39 @@
...
 
-interface CustomAppBarProps {
-    classes: ClassNameMap;
-}
-
-const Header = ({ classes }: CustomAppBarProps) => {
+export function Header() {
     return (
-        <AppBar position="static" className={classes.appBar}>
-            <Toolbar variant="dense" style={{ padding: '5px', display: 'flex', justifyContent: 'space-between' }}>
```
Comment (KevinWu098) [inline apps/antalmanac/src/components/Header/Header.tsx:40]: MUI v5 Toolbar is a gigantic pain to style, so we're opting to remove it

File: apps/antalmanac/src/components/RightPane/SectionTable/CourseInfo/CourseInfoButton.tsx
Comment (KevinWu098) [inline apps/antalmanac/src/components/RightPane/SectionTable/CourseInfo/CourseInfoButton.tsx:1]: In retrospect, having Zotistics and Enrollment data appear on hover was a pretty big degradation in user experience. Rendering in a large, visually blocking component on hover (which a user is going to inadvertently trigger simply by scrolling) is a pretty big no-no...

**Review by MinhxNguyen7 — APPROVED** [review]
Can't be that bad
