### PR TITLE
Fix bug by stripping string for condition checking

### LINKED ISSUE #390: Missing waypoints for course section with fake locations
If a section with a "fake" location (e.g. `TBA`, `VRTL REMOTE`, `ON LINE`) is present in a schedule, waypoints do not render properly on the map. The "all" view shows no waypoints or paths at all, and views for individual days show waypoints only if all sections with meetings that day have a real location. Any paths between sections with real locations are still rendered, though without waypoints.

### PR DESCRIPTION
**Pull request by JacE070**
## Summary
Fix the remaining missing-way-point bug by stripping the name of the building in sections.
Predecessor: https://github.com/icssc/AntAlmanac/pull/471
## Test Plan
I tested the cases that it only has sections with real locations, it only has sections with fake locations, and mixed.
The map functions well.
## Issues

Closes https://github.com/icssc/AntAlmanac/issues/390

### CODE REVIEW

File: src/components/RightPane/Map/UCIMap.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import '../../../../node_modules/leaflet.locatecontrol/dist/L.Control.Locate.min.js';
```
Comment (ap0nia) [inline src/components/RightPane/Map/UCIMap.tsx]:
```suggestion
```
Since you're in this file, could you try removing this line and see if the map still works? I'm pretty sure this is what the `import 'leaflet.locatecontrol'` line is supposed to do

File: src/components/RightPane/Map/UCIMap.tsx [hunk 2]
```diff
@@ -296,7 +296,7 @@ export default class UCIMap extends PureComponent {
                             !event.start.toString().includes(DAYS[day]) ||
                             courses.has(event.sectionCode) || // Remove duplicate courses that appear in the calendar
                             !courses.add(event.sectionCode) ||
-                            FAKE_LOCATIONS.includes(event.bldg)
+                            FAKE_LOCATIONS.includes(event.bldg.trim())
```
Comment (ap0nia) [inline src/components/RightPane/Map/UCIMap.tsx:300]: Good patch!

Do you know how this occurs? Ideally, we'd be handling the data in such a way that doesn't require us to patch it like this

**Review by ap0nia — APPROVED** [review]

File: src/components/RightPane/Map/UCIMap.tsx (hunk 2 above)
Comment (JacE070) [reply src/components/RightPane/Map/UCIMap.tsx:300]: I will inspect this! Thanks!

File: src/components/RightPane/Map/UCIMap.tsx (hunk 1 above)
Comment (JacE070) [reply src/components/RightPane/Map/UCIMap.tsx]: Yeah it works! Deleting this line is safe

File: src/components/RightPane/Map/UCIMap.tsx (hunk 2 above)
Comment (JacE070) [reply src/components/RightPane/Map/UCIMap.tsx:300]: Ok i'm sure the bldg field returned by PeterPortal api actually has a trailing whitespace when it's "TBA." So do you think this is a proper place to strip(trim) the bldg? @bevm0

Comment (ap0nia) [reply src/components/RightPane/Map/UCIMap.tsx:300]: Dang, what the heck, some of the "TBA" has embedded whitespaces in the HTML itself from the SOC, i.e. the `&nbsp;`
image

They might just be preserving that data and sending it to us. Yeah, I guess we can handle that here.

Can you just add a note somewhere, e.g. above `FAKE_LOCATIONS`, that the location data has inconsistent white spacing when received from the API, which motivates the trimming? We can merge it once that's done

Comment (JacE070) [reply src/components/RightPane/Map/UCIMap.tsx:300]: uhh I just saw your comment right after Eric merged it ; ( 

So the note hasn't been added yet...

Comment (EricPedley) [reply src/components/RightPane/Map/UCIMap.tsx:300]: Oops I didn't realize Brian wanted more changes on this 😐. 
I just read the comment and that change would be appreciated so just open another PR for it
